#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "Move config templates"
cp $OPENSHIFT_REPO_DIR/app/config/parameters.yml.env_template $OPENSHIFT_REPO_DIR/config/app/parameters.yml

echo "Run composer:"
cd $OPENSHIFT_REPO_DIR
$OPENSHIFT_RUNTIME_DIR/bin/php composer.phar install --prefer-source=git