#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &


# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
# replace the $OPENSHIFT_INTERNAL_IP and $OPENSHIFT_INTERNAL_PORT before starting up the server

echo "Try start php-cgi:"
nohup $OPENSHIFT_RUNTIME_DIR/bin/php-cgi -b $OPENSHIFT_INTERNAL_IP:16123 > $OPENSHIFT_LOG_DIR/server.log 2>&1 &

echo "Try change ip and port parameter in nginx conf template:"
sed -e "s/`echo '$OPENSHIFT_IP:$OPENSHIFT_PORT'`/`echo $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT`/" $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf.template > $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf.tmp1
echo "Try change log dir parameter in nginx conf template:"
sed -e "s,`echo '$OPENSHIFT_LOG_DIR'`,`echo $OPENSHIFT_LOG_DIR`," $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf.tmp1 > $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf.tmp2
echo "Try change repo dir parameter in nginx conf template:"
sed -e "s,`echo '$OPENSHIFT_REPO_DIR'`,`echo $OPENSHIFT_REPO_DIR`," $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf.tmp2 > $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf
rm $OPENSHIFT_RUNTIME_DIR/conf/nginx.conf.tmp1
echo "Try run ngnix server"
nohup $OPENSHIFT_RUNTIME_DIR/sbin/nginx > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
