#!/bin/bash
# The logic to stop your application should be put in this script.
echo "Try kill testrubyserver.rb"
kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
echo "Try kill php-cgi"
kill `ps -ef | grep php-cgi | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
