language: php

php:
    - 5.3
    - 5.4

before_script:
    - mv app/config/parameters.yml.travis app/config/parameters.yml
    - php composer.phar install
    - php app/console doctrine:database:create --env=test
    - php app/console doctrine:schema:create --env=test

script:
    - phpunit -c app
    - php bin/behat @OperowoMainBundle