parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     operowo
    database_user:     postgres
    database_password: postgres

    database_test_driver:   pdo_pgsql
    database_test_host:     ~
    database_test_port:     ~
    database_test_name:     operowo_test
    database_test_user:     postgres
    database_test_password: postgres

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
